name: grecipe
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  sqflite:
  path:
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  get: ^4.6.1
  image_picker: ^0.8.4+11
  tflite: ^1.1.2
  http: ^0.13.4
  camera: ^0.9.4+16
  carousel_slider: ^4.0.0
  flutter_signin_button: ^2.0.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_auth_web: ^3.3.9
  google_sign_in: ^5.2.4
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  custom_radio_grouped_button: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/banners/
    - assets/images/icons/ingredient_icon/
    - assets/images/icons/expiration_icon/
    - assets/models/model.tflite
    - assets/models/label.txt
    - assets/json/recipe.json

fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 700
